#import "/_template/template.typ": template, tr, ln, ct, inline-tree
#show: template(
  title:      [Gradual Typing Reading Notes],
  date:       datetime(year: 2026, month: 04, day: 01, hour: 14, minute: 52, second: 14),
  tags:       (),
  identifier: "000T",
)

#inline-tree(
  title: "Notes on Gradual Type Inference"
)[
#let ce = math.scripts(sym.tilde.eq)
#let cl = math.scripts(sym.subset.eq.sq)
#let vdash = math.scripts(sym.tack.r)
#let vDash = math.scripts(sym.tack.r.double)
#let LBe = math.attach("LB", br: $e$)

#tr("wb:sv-GradualTypingUnificationbased-2008", show-metadata: true, expanded: false, disable-numbering: true)

In section 3, the authors discuss some examples where the naive "well-typed after substitution" approach fails. That implies some rules that gradual type inference should follow, which is formalized as below:

Let $cl$ be the relation of "less or equally informative" as defined in the paper. Let $e$ be a term, $alpha, beta, ...$ are the type variables in $e$, $S$ a substitution generated by the inference.

// Let $LBe(alpha)$ be the set of lower bounds on $alpha$ induced by the constraints on $e$, defined by:

// $
// LBe(alpha) = { sigma | C_e vdash sigma cl alpha }
// $

// In other words, $LBe(alpha)$ is the set of types that are less or equally informative than the type represented by $alpha$ according to the constraints generated by $e$.

#inline-tree(
  title: "Static conservativity",
  level: 3
)[
If $e$ contains no $?$, then $exists S, Gamma, tau. space S; Gamma vdash_g e : tau arrow.l.r.double exists S', Gamma', tau'. space S'; Gamma' vdash e : tau'$, i.e. $e$ is gradually well-typed iff it is statically well-typed.
]

#inline-tree(
  title: "Constraint-informativeness preservation",
  level: 3
)[
Suppose we have $Gamma vdash_g e : tau | C$. For any type $sigma$ and substitution $S vDash C$, $C vdash sigma cl alpha arrow.double S(sigma) cl S(alpha)$. That is, the inferred type for $alpha$ is at least as informative as any type that is less or equally informative than $alpha$ according to the constraints.
]

#inline-tree(
  title: "Minimal adequate solution",
  level: 3
)[
Let $S'$ be any substitution, $Gamma$ a typing context. If $exists tau. space S'; Gamma vdash_g e : tau$ (i.e. $e$ is gradually well-typed under $S'$) and $forall alpha. forall sigma in LBe(alpha). space sigma cl S'(alpha)$ (i.e. $S'$ satisfies the constraint-informativeness preservation), then $forall alpha. space S(alpha) cl S'(alpha)$, i.e. the inferred substitution $S$ does not overly generalize.

If we define $LBe(alpha) =^"def" {sigma | C_e vdash sigma cl alpha}$, then $S(alpha) = union.sq.big LBe(alpha)$.
]

#inline-tree(
  title: "No spurious dynamicity",
  level: 3
)[
This rule is implied by the previous rules, but it is worth stating explicitly: $S(alpha) = ? arrow.double union.sq.big LBe(alpha) = ?$. That is, if $?$ is the only type that is less or equally informative than $alpha$ according to the constraints, then the inferred type for $alpha$ must be $?$.
]

The constraint-informativeness preservation rule and minimal adequate solution rule together gives me a sense of abstract interpretation...
]