#import "/_template/template.typ": template, tr, ln, ct, inline-tree
#show: template(
  title:      [Rules for gradual type inference],
  date:       datetime(year: 2026, month: 04, day: 21, hour: 22, minute: 27, second: 28),
  tags:       (),
  identifier: "000V",
)

#let ce = math.scripts(sym.tilde.eq)
#let cl = math.scripts(sym.subset.eq.sq)
#let vdash = math.scripts(sym.tack.r)
#let vDash = math.scripts(sym.tack.r.double)
#let LBe = math.attach("LB", br: $e$)

In section 3 of #ln("wb:sv-GradualTypingUnificationbased-2008")[Gradual Typing with Unification-based Inference], the authors discuss some examples where the naive "well-typed after substitution" approach fails. That implies some rules that gradual type inference should follow, but these rules are never expressed explicitly even as "rules", not to mention formalization. The following are my attempt to extract and formalize these rules. Roughly speaking, the first three rules are from the three examples in that section in the 2008 paper, and the last rule is a direct consequence of the first three rules.

Let $cl$ be the relation of "less or equally informative" as defined in the paper. Let $e$ be a term, $alpha, beta, ...$ are the type variables in $e$, $S$ a substitution generated by the inference.

#inline-tree(
  title: "Static conservativity",
  level: 3
)[
If $e$ contains no $?$, then $exists S, Gamma, tau. space S; Gamma vdash_g e : tau arrow.l.r.double exists S', Gamma', tau'. space S'; Gamma' vdash e : tau'$, i.e. $e$ is gradually well-typed iff it is statically well-typed.
]

#inline-tree(
  title: "Constraint-informativeness preservation",
  level: 3
)[
Suppose we have $Gamma vdash_g e : tau | C$. For any type $sigma$ and substitution $S vDash C$, $C vdash sigma cl alpha arrow.double S(sigma) cl S(alpha)$. That is, the inferred type for $alpha$ is at least as informative as any type that is less or equally informative than $alpha$ according to the constraints.
]

#inline-tree(
  title: "Minimal adequate solution",
  level: 3
)[
  Let $S'$ be any substitution, $Gamma$ a typing context. If $exists tau. space S'; Gamma vdash_g e : tau$ (i.e. $e$ is gradually well-typed under $S'$) and forall $sigma$, $S vDash C$ and $C vdash sigma cl alpha$ implies $S'(sigma) cl S'(alpha)$ (i.e. $S'$ satisfies the constraint-informativeness preservation), then $S(alpha) cl S'(alpha)$, i.e. the inferred substitution $S$ is not overly specific.
]

#inline-tree(
  title: "No spurious dynamicity",
  level: 3
)[
This rule is implied by the previous rules, but it is worth stating explicitly. Define $LBe(alpha) =^"def" {sigma | C_e vdash sigma cl alpha}$, then the rule says $S(alpha) = ? arrow.double union.sq.big LBe(alpha) = ?$. That is, if $?$ is the only type that is less or equally informative than $alpha$ according to the constraints, then the inferred type for $alpha$ must be $?$.
]

It is not clear how these rules would handle more complex features like polymorphism, subtyping, etc.
