name: Build GitHub Pages

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Typst
        uses: typst-community/setup-typst@v4
        with:
          typst-version: ^0.14.2

      - name: Install Fonts
        run: |
          curl -LO https://github.com/alerque/libertinus/releases/download/v7.051/Libertinus-7.051.tar.zst
          tar -I zstd -xf Libertinus-7.051.tar.zst
          mkdir -p ~/.local/share/fonts/Libertinus
          mv Libertinus-7.051/static/OTF/*.otf ~/.local/share/fonts/

      - name: Build notes
        run: |
          cargo install --locked --git https://github.com/hanwenguo/weibian.git
          wb compile

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: hanwenguo/hanwenguo.github.io
          publish_dir: ./dist
          commit_message: ${{ github.event.head_commit.message }}
          
